### ISSUE TITLE
More meaningful/human errors for `lagoon list variables`

### ISSUE THREAD

**Issue by klonos** [amazeeio/lagoon-cli#105]
Current behavior:

```
lagoon list variables -p some-project-that-exists
Error: no data returned from the lagoon api
```

```
lagoon list variables -p some-project-that-doesnt-exist
Error: graphql: Cannot read property 'id' of undefined
```

These errors could instead be:

`No variables defined for project some-project-that-exists`

`Project some-project-that-doesnt-exist not found`

**Comment by shreddedbacon** [comment]
@klonos I have PR #153 that will hopefully solve most of this.

```
$ lagoon list variables -p drupal-example -e main
Info: There are no variables for environment 'main' in project 'drupal-example'
```
and
```
$ lagoon get project -p non-existent-project
Error: GraphQL API returned a null response, the requested resource may not exist, or there was an error. Use `--debug` to check what was returned
```

---

In your original issue note, you have this error. This is not because the project doesn't exist, there is a bit more to it.
```
lagoon list variables -p some-project-that-doesnt-exist
Error: graphql: Cannot read property 'id' of undefined
```

This is typically because the local git repository check in the CLI is injecting the branch in your current working directory into your query, the CLI obfuscates the real issue a bit by not letting you know that it is injecting an environment name into the query. 
There is another fix that will come to the CLI that will help with that particular issue soon.
