### ISSUE TITLE
Bulk import environment variables

### ISSUE THREAD

**Issue by seanhamlin** [amazeeio/lagoon-cli#119]
**Is your feature request related to a problem? Please describe.**

It is common for env vars to be specified in a 1 per line format, something like:

```
NAME=value
ANOTHER_NAME='another value with a space'
```

There is currently no easy way to import a lot of these vars into Lagoon.

**Describe the solution you'd like**

I would love a way to ingest env vars in this format. Trying to create the YAML format required by the `import` command at the moment is very time consuming.

**Describe alternatives you've considered**

This script is super hacky, but gets the job done.

```php
#!/usr/bin/env php
<?php

foreach(file("/tmp/vars.txt") as $line) {
  $output = [];
  $parts = explode('=', $line, 2);
  $name = strtoupper($parts[0]);

  // Skip comments.
  if (preg_match('/^#/', $name)) {
    continue;
  }

  $value = trim($parts[1]);

  exec("lagoon -l amazeeio add variable -p $PROJECT -e $BRANCH -N {$name} -V '{$value}' -S runtime 2>&1", $output);
  print_r($output);
}

echo "\n\n DONE\n";
```

**Comment by smlx** [comment]
I don't know if this belongs in `lagoon-cli`.. it seems like it might be better off as documentation.
The problem is that there are going to be lots of edge cases in the formatting and logic (are the names or values quoted or escaped? are they all from the same project/environment? are they all the same scope?). Also there is no efficiency gain because there is no "bulk envvariable" API, so it will be a single request per variable exactly as if you called `lagoon` once per variable.

I came up with this, maybe it could go into the documentation? The advantage is that you can remove the `| sh` at the end and get a preview of the script.
```
(echo set -xeu; awk -F= '{print "lagoon -l local add variable -p myproject -e mybranch -S global -N " $1 " -V " $2}' /tmp/vars.txt) | sh
```

**Comment by seanhamlin** [comment]
Yeah, docs could be a good answer to this. One thing with your script, env vars can have `=` in the value, so you don't want to split on that. The PHP script limits the splitting to the first`=` only.

**Comment by smlx** [comment]
Ah, good point. Amended snippet:
```
(echo set -xeu; awk -F= '/^[^#]/ {sep=index($0,"="); print "lagoon -l local add variable -p myproject -e mybranch -S global -N " $1 " -V " substr($0,sep+1)}' /tmp/vars.txt) | sh
```
