### ISSUE TITLE
Cannot decode encrypted private keys

### ISSUE THREAD

**Issue by DIOHz0r** [amazeeio/lagoon-cli#172]
**Describe the bug**
I'm trying to use lagoon cli but I'm getting an error with the message "ssh: cannot decode encrypted private keys"

**To Reproduce**
1. Go to a project folder
2. Run "lagoon list project"
3. See error "Error was: ssh: cannot decode encrypted private keys"

**Expected behavior**
Get the project list

**Desktop (please complete the following information):**
 - OS: macOs BigSur
 - Browser N/A
 - Version N/A

**Comment by shreddedbacon** [comment]
Hi @DIOHz0r,  this is because there is no way for the CLI to decode the encrypted private key.

The best way is to use ssh-agent, you can add your encrypted key to the agent using `ssh-add` and this will ask you for your keys password to load it in. Once the key is in the agent, the CLI will use the keys in your agent to authenticate with Lagoon.

The error message could be better here, I'll flag this for correction, and get some documentation written up.
